<?php

namespace Infocorp\Bundle\SintufBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CovenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CovenantRepository extends EntityRepository
{
}
