<?php

namespace Infocorp\Bundle\SintufBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedRepository extends EntityRepository implements SlideInterface
{
    /**
     * {@inheritdoc}
     */
    public function findLastSlides($limit = null)
    {
        $qb = $this->createQueryBuilder('p');
            
        $qb->where('p.enabled = true')
            ->andWhere($qb->expr()->isNotNull('p.image'))
        ;
        if ($limit) {
            $qb->setMaxResults($limit);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}