infocorp_sintuf_homepage:
    path:  /
    defaults: { _controller: InfocorpSintufBundle:Home:index }

infocorp_sintuf_noticias:
    path: /noticias
    defaults: { _controller: InfocorpSintufBundle:News:index }

infocorp_sintuf_noticia:
    path: /noticias/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:view }

infocorp_sintuf_noticias_list_home:
    path: /noticias-list-home
    defaults: { _controller: InfocorpSintufBundle:News:homeList }

infocorp_sintuf_noticias_categoria:
    path: /noticias/categoria/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:category }

infocorp_sintuf_fale_conosco:
    path: /fale-conosco
    defaults: { _controller: InfocorpSintufBundle:Contact:email }

infocorp_sintuf_slider:
    path: /slide
    defaults: { _controller: InfocorpSintufBundle:Slide:index }

infocorp_sintuf_institutional_list:
    path: /institucional-list
    defaults: { _controller: InfocorpSintufBundle:Institutional:list }

infocorp_sintuf_institutional_view:
    path: /institucional/{slug}
    defaults: { _controller: InfocorpSintufBundle:Institutional:view }

infocorp_sintuf_galeria:
    path: /galerias
    defaults: { _controller: InfocorpSintufBundle:Gallery:index }

infocorp_sintuf_galeria_view:
    path: /galerias/{id}
    defaults: { _controller: InfocorpSintufBundle:Gallery:view }

infocorp_news_add_comment:
    path: /add-comment/{id}
    defaults: { _controller: ApplicationSonataNewsBundle:ApplicationPost:addComment }
    methods: [POST]