infocorp_sintuf_homepage:
    pattern:  /
    defaults: { _controller: InfocorpSintufBundle:Home:index }

infocorp_sintuf_noticias:
    pattern: /noticias
    defaults: { _controller: InfocorpSintufBundle:News:index }

infocorp_sintuf_noticia:
    pattern: /noticias/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:view }

infocorp_sintuf_noticias_categoria:
    pattern: /noticias/categoria/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:category }

infocorp_sintuf_fale_conosco:
    pattern: /fale-conosco
    defaults: { _controller: InfocorpSintufBundle:Contact:email }

infocorp_sintuf_slider:
    path: /slide
    defaults: { _controller: InfocorpSintufBundle:Slide:index }

infocorp_sintuf_institutional_list:
    path: /institucional-list
    defaults: { _controller: InfocorpSintufBundle:Institutional:list }

infocorp_sintuf_institutional_view:
    pattern: /institucional/{slug}
    defaults: { _controller: InfocorpSintufBundle:Institutional:view }

infocorp_sintuf_galeria:
    pattern: /galerias
    defaults: { _controller: InfocorpSintufBundle:Gallery:index }

infocorp_sintuf_galeria_view:
    pattern: /galerias/{id}
    defaults: { _controller: InfocorpSintufBundle:Gallery:view }