infocorp_sintuf_homepage:
    path:  /
    defaults: { _controller: InfocorpSintufBundle:Home:index }

infocorp_sintuf_noticias:
    path: /noticias
    defaults: { _controller: InfocorpSintufBundle:News:index }

infocorp_sintuf_noticia:
    path: /noticias/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:view }

infocorp_sintuf_noticias_list_home:
    path: /noticias-list-home
    defaults: { _controller: InfocorpSintufBundle:News:homeList }

infocorp_sintuf_noticias_categoria:
    path: /noticias/categoria/{slug}
    defaults: { _controller: InfocorpSintufBundle:News:category }

infocorp_sintuf_fale_conosco:
    path: /fale-conosco
    defaults: { _controller: InfocorpSintufBundle:Contact:email }

infocorp_sintuf_slider:
    path: /slide
    defaults: { _controller: InfocorpSintufBundle:Slide:index }

infocorp_sintuf_institutional_list:
    path: /institucional
    defaults: { _controller: InfocorpSintufBundle:Institutional:list }

infocorp_sintuf_institutional_view:
    path: /institucional/{slug}
    defaults: { _controller: InfocorpSintufBundle:Institutional:view }

infocorp_sintuf_direction_list:
    path: /direcao
    defaults: { _controller: InfocorpSintufBundle:Direction:list }

infocorp_sintuf_direction_view:
    path: /direcao/{slug}
    defaults: { _controller: InfocorpSintufBundle:Direction:view }

infocorp_sintuf_galeria:
    path: /galerias
    defaults: { _controller: InfocorpSintufBundle:Gallery:index }

infocorp_sintuf_galeria_view:
    path: /galerias/{id}
    defaults: { _controller: InfocorpSintufBundle:Gallery:view }

infocorp_news_add_comment:
    path: /add-comment/{id}
    defaults: { _controller: ApplicationSonataNewsBundle:ApplicationPost:addComment }
    methods: [POST]

sintuf_affiliate:
    path: /afilie-se
    defaults: { _controller: InfocorpSintufBundle:Affiliate:index }

infocorp_sintuf_covenant_list:
    path: /convenios
    defaults: { _controller: InfocorpSintufBundle:Covenant:list }

infocorp_sintuf_covenant_view:
    path: /convenios/{slug}
    defaults: { _controller: InfocorpSintufBundle:Covenant:view }

infocorp_sintuf_partner_list:
    path: /parceiros
    defaults: { _controller: InfocorpSintufBundle:Partner:list }

infocorp_sintuf_partner_list_home:
    path: /partner-list-home
    defaults: { _controller: InfocorpSintufBundle:Partner:homeList }

infocorp_sintuf_partner_view:
    path: /parceiros/{slug}
    defaults: { _controller: InfocorpSintufBundle:Partner:view }