parameters:
#    infocorp_affemat.example.class: Infocorp\Bundle\SintufBundle\Example

services:
    sonata.admin.featured:
        class: Infocorp\Bundle\SintufBundle\Admin\FeaturedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Destaques }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Featured, null]

    sonata.admin.institutional:
        class: Infocorp\Bundle\SintufBundle\Admin\InstitutionalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Institucional }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Institutional, null]

    sonata.admin.direction:
        class: Infocorp\Bundle\SintufBundle\Admin\DirectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Direção }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Direction, null]

    sonata.admin.covenant:
        class: Infocorp\Bundle\SintufBundle\Admin\CovenantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Convênio }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Covenant, null]

    sonata.admin.partner:
        class: Infocorp\Bundle\SintufBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Parceiros }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Partner, null]

    sintuf.form.type.affiliate:
        class: Infocorp\Bundle\SintufBundle\Form\AffiliateType
        tags: 
            - { name: form.type, alias: form_affiliate }

    sonata.admin.menu:
        class: Infocorp\Bundle\SintufBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Menu }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Menu, null]

    sonata.admin.affiliate:
        class: Infocorp\Bundle\SintufBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Afiliados, label: Afiliados }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Affiliate, null]
