parameters:
#    infocorp_affemat.example.class: Infocorp\Bundle\SintufBundle\Example

services:
    sonata.admin.featured:
        class: Infocorp\Bundle\SintufBundle\Admin\FeaturedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Destaques }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Featured, null]

    sonata.admin.institutional:
        class: Infocorp\Bundle\SintufBundle\Admin\InstitutionalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Site, label: Institucional }
        arguments: [null, Infocorp\Bundle\SintufBundle\Entity\Institutional, null]

    sintuf.form.type.affiliate:
        class: Infocorp\Bundle\SintufBundle\Form\AffiliateType
        tags: 
            - { name: form.type, alias: form_affiliate }